
services:
  inventory-management-app:
    depends_on:
      - db
    build: 
      context: .
      dockerfile: Dockerfile
    image: inventory-management-docker
    container_name: inventory-management-app
    ports:
      - "${PORT}:${PORT}"
   
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      PORT: ${PORT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}

  db:
    image: postgres:16
    container_name: inventory-management-db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
    volumes:
      - ./postgres:/var/lib/postgresql/data